OSS layout fixes and aggregated core and example updates.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,4 +1,4 @@
-sudo: false
+os: linux
 notifications:
   email: false
 dist: xenial
@@ -21,4 +21,19 @@ install:
   - conda install --yes python=$TRAVIS_PYTHON_VERSION pip absl-py opt_einsum numpy scipy pytest-xdist pytest-benchmark
   - pip install jaxlib jax
   - pip install -v .
-script: pytest -n 1 tests examples -W ignore ;
+script:
+  # make default temporary dir for absl tests
+  - mkdir /tmp/absl_testing
+  # run the main flax unit tests
+  - pytest -n 1 tests -W ignore
+  # we apply pytest within each example to avoid pytest's annoying test-filename collision.
+  # In pytest foo/bar/baz_test.py and baz/bleep/baz_test.py will collide and error out when
+  # /foo/bar and /baz/bleep aren't set up as packages.
+  - |
+    for egd in $(find examples -maxdepth 1 -mindepth 1 -type d); do
+      pytest -n 1 $egd -W ignore
+      # Pytest returns error code 5 for no found tests, but don't forward this as an error.
+      # We may remove this to force minimal test coverage in the future!
+      ret=$?
+      if [[ "$ret" != 0 ]] && [[ "$ret" != 5 ]]; then exit 1; fi
+    done
